background_opacity: 0.94

selection:
  save_to_clipboard: true

font:
  size: 8
  normal:
    family: "Cascadia Mono"
       
window:
  padding:
    x: 10
    y: 10

import:
  - /home/theocodes/.config/alacritty/molokai.yml
